### ISSUE TITLE
Replace `RolesStorageInterface::getChildren()` to `getItemParents()`

### ISSUE THREAD

**Issue by vjik** [yiisoft/rbac#110]
`RolesStorageInterface::getChildren()` used in two places.

1. Access check

https://github.com/yiisoft/rbac/blob/37a0fe51e37de5925154e32cd9c19a2ae0d294f0/src/Manager.php#L634-L667

This is very not optimal: each call `userHasItem()` (this is recursive method) we request chidlren from storage.

2. Receiving user IDs assigned to the role specified

https://github.com/yiisoft/rbac/blob/37a0fe51e37de5925154e32cd9c19a2ae0d294f0/src/Manager.php#L343-L358
https://github.com/yiisoft/rbac/blob/37a0fe51e37de5925154e32cd9c19a2ae0d294f0/src/Manager.php#L534-L545

### Suggestion

Seems in both places `getChildren()` can be replaced to method `getItemParents(string $name): Item` and it will be more more performance solution.

**Comment by samdark** [comment]
It changes interface so should be tried before first release.

The solution would likely require changes in PHP storage. Currently the structure is:

```php
'parent1' => [
    'child1' => Item1,
    'child2' => Item2,
],
'parent2' => [
    'child1' => Item,
    'child3' => Item,
],
```

That is good for finding children of a certain parent with O(1) but isn't good for fiding parents of a certain child with O(parentsN + childrenN).

An additional structure such as the following may be required to make it O(1) as well:

```php
$parents = [
    'child1' => [
        'parent1',
        'parent2',
    ],
     'child2' => [
        'parent1',
    ],
    'child3' => [
        'parent2',
    ],
];
```

The structure needs to be updated on loading from file, renaming items, adding a child etc.

Likely that won't give any additional performance benefit on typical RBAC hierarchy since it is likely to be small. Especially if `getChildren()` is cached.

**Comment by vjik** [comment]
For `Manager`, getting all children is redundant. He only needs parents. We can change interface to getting parents, but into storage implement this via getting all children. This way wi will not have to change PHP-storage structure and, if necessary, will allow to write a more optimized storage.
