### ISSUE TITLE
AccessControl filter does not support RBAC rules

### ISSUE THREAD

**Issue by mrbig** [yiisoft/rbac#17]
### Problem description

[RBAC rules](http://www.yiiframework.com/doc-2.0/guide-security-authorization.html#using-rules) are very useful to solve complex authorization problems. Unfortunately the AccessControl filter does not support them out of the box because custom parameters can not be fed to the roles. So one must use each time the matchCallback with custom implementation, but it results in such non elegant access rules where the real role check is hidden in the callback:

``` 
[
    'allow' => true,
    'roles' => ['@'],
    'matchCallback' => function($rule, $action) {
        return Yii::$app->user->can('updateOwnPost', ['postId' => 2]);
    }
]
```

### Proposed solution

Here I'm proposing a solution to add an optional ruleParamsCallback which should return any parameters necessary for the User::can check. For example:

```
[
    'allow' => true,
    'roles' => ['updateOwnPost'],
    'ruleParamsCallback' => function($rule, $action, $role) {
        return ['postId' => 12];
    }
]
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.12
| PHP version      | any
| Operating system | any

**Comment by nd4c** [comment]
This is just some brain storming.  Trying to think outside the box.

With the current implementation of the ACF and RBAC I kind of favor @arogachev - it just seems like you're dealing with the specifics where the specifics are needed.  That said...

> Several duplicate issues already exist: #7643, #13273, #13552.
> 
> I think I explained well why this should not be implemented in [yiisoft/yii2#13273 (comment)](https://github.com/yiisoft/yii2/issues/13273#issuecomment-269185026).

If this is the fourth issue considering incorporating RBAC into the ACF, then maybe the current implementation of the ACF needs to be revisited.  It is after all the Access Control Filter.  You would think that's where you would handle the Access Control whether you are using RBAC or not.  Like a cross-cutting concern.

There are two drawbacks that I can think of to using the ACF to handle any RBAC with Rules.
[ ] Having to pre-access any data models before even getting to the Action.  Caching can help, but I don't think caching should be the solution.  There would need to be a way for the ACF to pass in any data it pre-access to the Action if access is allowed.
[ ] Controllers and Action methods are just php.  There is nothing to prevent one Action from calling another Action directly - not via a redirect.  That direct call would completely bypass the ACF. {Who does this!? I don't know, but it's possible - so we should consider it...}

Maybe ACF should be handled right in the Action itself.  This would be more like a typical cross-cutting concern.  You put the call to the Concern _where_ it's concerned.  The only benefit to having an ACF isolated in a configuration method is that it can send the user to login if needed before even calling the action.  But I think that's a minimal use case.  The vast majority of Access Control is going to be handled better after we get to the Action.  Each Action could handle it's own redirects or exceptions as best needed.

And currently you add an Action and you also have to make sure the action is listed in the ACF, so you are bouncing between two different sections of the controller.  With ACF in the Action, you add in the Action and specify the ACF requirements first thing in the Action itself right where you are typing in your code.

Why even have ACF?  Well for when RBAC is not needed.  Also the simple check for a required Login.  The trick would be to make the coding a light as possible.  Like methods named loginAndCan() or something.  Actually it's quite simple any call to ACF/RBAC would assume they need to be logged in.  Otherwise just don't call any access control methods.

**Comment by samdark** [comment]
Re-reading it all and getting to @nd4c made me realize that ACF itself isn't really needed and direct calls are actually much cleaner and safer.

**Comment by nd4c** [comment]
@samdark I realize that this is closed and I agree that ACF isn't really needed.  

However, please let me point out that it did one thing really well if it was configured correctly (ie: having ['allow' => false] as the last element of the 'rules') - it prevented a developer from forgetting to add in access control.  The action would fail until something was done about access control.

It would be nice to have some way to have all actions unaccessible by default (or not).  This could be a property of the base controller that all controllers extend from.  It could even have the base controller beforeAction check if rbac is enabled or not and preset it one way or another.

Sorry if this seems kind of paranoid. ;)

**Comment by samdark** [comment]
Yes, that's one of the things that could not be achieved without actions filter. Will see what we can do but for now I think sticking with no ACF is better.

**Comment by nd4c** [comment]
I agree that the ACF is not needed.  I've been trying to think of a way to incorporate the few benefits of the ACF.  Since we aren't running RBAC (or ACF) before the Action, there is no way in the Action to "require" some kind of rbac decision as the first thing in the action.  (Maybe that will be some kind of future function construct.)  For now the easiest way to do this would be to extend the base Controller into an rbac controller which would pass the rbac manager as the first parameter to the action.  It would be kind of hard to forget at that point.  For someone building an rbac app this kind of emphasizes the security without actually doing anything preset - it's still up to the programmer to management as seems best.  Again, this might be overkill.  Just want to share some ideas.

**Comment by hiqsol** [comment]
Just my 5 cents ;)
We've created and happily using this implementation for quite some time:
https://github.com/hiqdev/hipanel-core/blob/master/src/filters/EasyAccessControl.php

Here is an example of usage:
https://github.com/hiqdev/hipanel-module-client/blob/master/src/controllers/ClientController.php#L39

It works fine for us. But your mileage may vary.
And I absolutely agree with previous comments that the same effect could be achieved with other means.
